-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 13:51:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TCDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TCDatabase` ;

-- -----------------------------------------------------
-- Schema TCDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TCDatabase` DEFAULT CHARACTER SET utf8 ;
USE `TCDatabase` ;

-- -----------------------------------------------------
-- Table `TCDatabase`.`CenterType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCDatabase`.`CenterType` ;

CREATE TABLE IF NOT EXISTS `TCDatabase`.`CenterType` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Value` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCDatabase`.`Center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCDatabase`.`Center` ;

CREATE TABLE IF NOT EXISTS `TCDatabase`.`Center` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `StreetAddress` VARCHAR(200) NULL,
  `CenterTypeId` INT NOT NULL,
  `CenterTypeDesc` VARCHAR(500) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Center_CenterType_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `TCDatabase`.`CenterType` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TCDatabase`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TCDatabase`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `TCDatabase`.`Appointment` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ClientFullName` VARCHAR(200) NOT NULL,
  `Date` DATE NOT NULL,
  `Center` INT NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Appointment_Center_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `TCDatabase`.`Center` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
